version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env.dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
