version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
