# Generated by Django 5.2.7 on 2025-10-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='method',
            field=models.CharField(default='GET', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlog',
            name='url',
            field=models.CharField(default='test/', max_length=2048),
            preserve_default=False,
        ),
    ]
