# Generated by Django 5.2.7 on 2025-10-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_groupederror_errorlog_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=2048)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('avg_duration_ms', models.PositiveIntegerField(default=0)),
                ('p50_duration_ms', models.PositiveIntegerField(default=0)),
                ('p95_duration_ms', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='telemetry.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('project', 'url', 'timestamp')},
            },
        ),
    ]
