# Generated by Django 5.2.7 on 2025-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_alter_project_options_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupederror',
            name='url',
            field=models.CharField(default='test/', max_length=2048),
            preserve_default=False,
        ),
    ]
